[package]
name = "pingpong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrome_native_messaging = "0.3.0"
serde_json = "1.0.61"
serde = { version = "1.0.118", features = ["derive"] }